# Generated by Django 3.2.16 on 2023-01-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/def.jpg', upload_to='blog/'),
        ),
    ]
